- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 3600
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: PlayerBorgMedical