- type: inventoryTemplate
  id: droid
  slots:
    - name: head
      slotTexture: head
      slotFlags: HEAD
      uiWindowPos: 1,0
      strippingWindowPos: 1,0
      displayName: Head
      offset: 0.02, 0
    - name: back
      slotTexture: back
      fullTextureName: template_small
      slotFlags: BACK
      slotGroup: SecondHotbar
      uiWindowPos: 2,0
      strippingWindowPos: 2,0
      displayName: Back
