- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      time: 1
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
  startingGear: RobotGear # for char preview only

- type: startingGear
  id: RobotGear
  equipment:
    head: ClothingHeadHatCardborg
    outerClothing: ClothingOuterCardborg