- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Justice
      time: 7200
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Command
  - External
  - Lawyer
  - Security
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: IAAGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    neck: ClothingNeckLawyerbadge
  inhand:
    - BriefcaseIAAFilled
